# Generated by Django 3.0.6 on 2021-01-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
