# Generated by Django 3.0.6 on 2021-01-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalner', '0002_auto_20210108_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price_per_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
